.prettierrc.json, .stylelintrc.json, package-lock.json, package.json, src/stylesheets/components/message.scss
=> lintで世界平和を作りたかった

.editorconfig, .stylelintrc.json, circle.yml, package.json, src/stylesheets/application.scss, src/stylesheets/common.scss
=> setup circleci

src/typescripts/infrastructure/api_client.ts, src/typescripts/infrastructure/index.ts
=> add ApiClient

src/stylesheets/application.scss, src/stylesheets/components/loading.scss, src/typescripts/app.tsx, src/typescripts/components/index.ts, src/typescripts/components/loading.tsx, src/typescripts/screens/root.tsx
=> add 'Loading' component

index.html, package-lock.json, src/stylesheets/components/products.scss, src/typescripts/screens/root.tsx, src/typescripts/screens/screen.tsx
#34 
入れるとかいいながらCDNなので特に変更はない。
react-bootstrap VS reactstrap...どちらも更新されていてビミョいなと思った結果CDNになった
=> bootstrap入れる

package-lock.json, package.json, public/index.html, src/typescripts/screens/product_show.tsx, src/typescripts/screens/products.tsx, src/typescripts/services/photo.ts, webpack/dev.js
'webpack-serve'文献ないし調べるのめんどくさそうだから`webpack-dev-server`にしたけど詰まったから `webpack-serve`にしてみようかしら。
#13
わからん
> http://localhost:8080/products
> http://localhost:8080/products/1
上だとリロードしても生きてるのに下だとReloadしたあと404になる
=> ReactRouterで404になっちゃう

.editorconfig, README.md
=> ざっくりと現状のDir構成についてまとめる

src/stylesheets/screens/product_show.scss, src/typescripts/screens/product_show.tsx, src/typescripts/services/photo.ts, src/typescripts/services/product.ts
=> Create product show

src/typescripts/components/product_votes_list.tsx, src/typescripts/screens/product_vote.tsx, src/typescripts/services/product.ts, src/typescripts/services/user.ts
=> Refactor some bugs

src/typescripts/components/header.tsx, src/typescripts/screens/not_found.tsx
=> アプリとしてのトップは'/products'に統一

public/index.html, src/stylesheets/components/header.scss, src/stylesheets/screens/product_show.scss, src/typescripts/screens/product_show.tsx
=> app.js読み込み修正／詳細ページCSS調整

src/stylesheets/screens/product_show.scss, src/typescripts/screens/product_show.tsx
=> 画像切り替えをそれっぽく実装

src/stylesheets/application.scss, src/stylesheets/common.scss, src/stylesheets/components/modal.scss, src/stylesheets/screens/product_show.scss, src/typescripts/components/index.ts, src/typescripts/components/modal.tsx, src/typescripts/screens/product_show.tsx, tslint.json
=> 投票完了画面をモーダルで出す

src/typescripts/components/index.ts, src/typescripts/components/product_show_footer.tsx, src/typescripts/screens/product_show.tsx
Footerってコンポーネント二つあるの見通し悪いけど一旦無視します。
=> product_show_footerがexportされてないなどのバグ修正

src/typescripts/app.tsx, src/typescripts/services/index.ts, src/typescripts/services/initialization.ts
=> シークレットブラウザでのぞいてきた人は追い出す

public/index.html
=> いつまでもhelloしたくない

.circleci/config.yml
buildとdeployの方も`-stretch`つけたのでこれでgitのバージョン上がって問題ないはず
=> fix "build", "deploy" jobs image.

.circleci/config.yml
=> add memory config for circleci

.circleci/config.yml, package.json, tslint.json
tslintのコンフィグ弄ってnode_modulesとpublic参照しないようにしたのと
circleciのlint走らせるときに.tsも見るようにした
cssは知らん
=> fix tslint config and add .ts lint for circleci

package.json, src/typescripts/services/photo.ts
=> cloudfrontに対応したい

src/typescripts/screens/product_show.tsx
- product show のパフォーマンス修正
- 投票取り消しの際の不具合
=> Fix vote btn label

src/stylesheets/components/product.scss, src/stylesheets/screens/products.scss, src/typescripts/components/product.tsx
=> product一覧に番号付与

src/typescripts/application_manager.ts, src/typescripts/entities/product.ts, src/typescripts/screens/product_show.tsx, src/typescripts/services/vote.ts
=> ボタン押された時に一旦無効化する様に

src/stylesheets/components/product_votes_list.scss, src/stylesheets/screens/product_show.scss, src/typescripts/screens/product_show.tsx
=> 投票完了モーダルをいい感じにしたかった

src/stylesheets/components/header.scss, src/stylesheets/screens/product_show.scss, src/typescripts/components/header.tsx, src/typescripts/components/product.tsx, src/typescripts/entities/product_list.ts, src/typescripts/screens/product_show.tsx, src/typescripts/services/product.ts
=> 一覧と詳細画面の表示変更／当たり判定強化

src/stylesheets/components/product.scss, src/stylesheets/components/tab.scss, src/stylesheets/screens/product_show.scss, src/typescripts/components/index.ts, src/typescripts/components/view_image_mask.tsx, src/typescripts/screens/product_show.tsx
- 一覧のカードのデザイン微調整
- 詳細ページの微調整
- footerのタブ選択色変更
=> CSSを調整するなどしました
